# Site settings
title: Jae-Yeong Lee
email: roricljy@gmail.com
description: ""
baseurl: ""
url: "https://roricljy.github.io"
github_username:  roricljy

# Build settings
markdown: "kramdown"

# Other options
#permalink: blog/:year/:month/:title
job.title: "Ph.D"
excerpt_separator: "<!--more-->"
